version: '3'

volumes:
  local_postgres_data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 5431:5432