# Generated by Django 3.2.12 on 2022-05-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ('id', 'parent_id'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ('organization_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'ordering': ('organization_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.organization', verbose_name='Organization')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='organization.tariff', verbose_name='Tariff')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='organization.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('organization_id', 'id'),
            },
        ),
    ]
